# Generated by Django 2.0 on 2020-03-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20200317_1954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signer_mobile',
            new_name='singer_mobile',
        ),
    ]
